### PR TITLE
parse slack text message with url to raw

### PR DESCRIPTION
**Pull request by dwdraju**
Parse slack posted url that converts: `<http://gcr.io|gcr.io>` into `gcr.io`.

### CODE REVIEW

**Comment by doenietzomoeilijk** [comment]
Is this something you'd really want to do in each and every slack message, unconditionally, without it being aware of the string being an actual URL or just something a user dumped between angle brackets? To me it feels like this is something you'd do in your actual commands, on a "I need this cleaned up in this case" base (and then it'd be useful for other networks as well), but maybe that's just me.

**Comment by fabioxgn** [comment]
I agree with @doenietzomoeilijk also there's already a `RunWithFilter` method with runs the bot and passes the message to a provided method, isn't this what you need?

**Comment by dwdraju** [comment]
I agree it may not be a best way to apply unconditionally but I think this issue is to be addressed by some way. As slack could include link markup on any raw(expected) text, there has to be some way.

@fabioxgn thanks for pointing.

**Comment by fabioxgn** [comment]
I don't think that this kind of parsing must be done by the bot, as there is a solution using a custom filter, I'll close this PR.

**Pull request closed without merging**
