### PR TITLE
Support for multiple periodic commands

### PR DESCRIPTION
**Pull request by zachomedia**
Adds the ability to have multiple periodic commands registered.

### CODE REVIEW

**Comment by fabioxgn** [comment]
The build broke with a race condition, can you please run the tests with `-race` flag and fix it? Thanks.

**Comment by zachomedia** [comment]
@fabioxgn Sorry about that, still new to go. I changed `startPeriodicCommands` to not be async anymore.

**Comment by fabioxgn** [comment]
@zachomedia thanks, please send a new PR when you are done.

I also noticed that some plugins are broken and were breaking the build, so I removed then from the build process, will try to fix the build process in the PRs which are broken.

**Comment by zachomedia** [comment]
PR #51 submitted with the fix

**Pull request merged**
